name: Hello workflow
on:
  push:
    branches: ["main"]
    

jobs:
  build:
     uses: helloquang/learning-ci/.github/workflows/build-workflow.yml@main
     with:
       node-version: '20.x'
     permissions:
       pages: write
       id-token: write
    
